#!/bin/sh
#

apk add nginx

chmod +x /tmp/entrypoint

cp -av /tmp/entrypoint /sbin/
cp -av /tmp/nginx.conf /etc/nginx/http.d/default.conf

######

cd /var/www

if [ ! -d /var/www/api ]; then
    wget https://github.com/imsyy/DailyHotApi/archive/refs/tags/v2.0.4.tar.gz
    tar xvf v2.0.4.tar.gz && mv DailyHotApi-2.0.4 front-build
    rm -f v2.0.4.tar.gz
fi

cd /var/www/api

[ -d node_modules ] || npm i

######

cd /var/www

if [ ! -d /var/www/front-build ]; then
    wget https://github.com/imsyy/DailyHot/archive/refs/tags/v1.1.0.tar.gz
    tar xvf v1.1.0.tar.gz && mv DailyHot-1.1.0 api
    rm -f v1.1.0.tar.gz
fi

cd /var/www/front-build

sed -i "s|Copyright By|$(date +'%Y')|" src/components/Footer.vue
sed -i 's|"author": "imsyy"|"author": "APP_COPYRIGHT"|' package.json
sed -i 's|"github": "https://github.com/imsyy"|"github": "APP_COPYRIGHT_URL"|' package.json

echo "VITE_GLOBAL_API=/api" >.env
echo "VITE_ICP=APP_ICP" >>.env
echo "VITE_DIR=/" >>.env

[ -d node_modules ] || npm i
[ -d dist ] || npm run build

mv dist /var/www/front
rm -rf /var/www/front-build

######

rm -rf /tmp/*
